### ISSUE TITLE
Copy File does not work as intended

### ISSUE THREAD

**Issue by nzejdlik** [blue-prism/file-management-utility#1]
The description, pre/post conditions, and parameter info on Copy File indicate _a_ file will be copied. However, the code is actually copying multiple files if a wildcard is used. Additionally, if wildcards are not used and the source file does not exist, it will incorrectly Success as True.

Suggest having two distinct actions: Copy File, specific for a single file, and Copy Files for wildcard matching.

**Comment by EricWilson-BluePrism** [comment]
Hi @nzejdlik ,

Can you tell me which version of Blue Prism you're working with? I've just run a few tests and as far as the case of the file not existing it conerned, I receive **Success = False** the and the message **No files found**.

Cheers,
Eric

**Comment by nzejdlik** [comment]
Version 5.24 (a wee bit dated). To test, I grabbed the code out of the XML and popped it into Visual Studio, and came up with the same result. The issue seems to be this line in particular: `Dim aFiles As FileInfo() = objDirectoryInfo.GetFiles(sSourceFileName)`

If the directory exists but sSourceFileName doesn't exist in the directory, then it returns an empty FileInfo array, which causes it to skip to the `Success = True` line.

**Comment by EricWilson-BluePrism** [comment]
@nzejdlik I've just pushed a new version of the VBO to the GitHub repos that addresses the issue of the Success flag. There's an extra check to see if the array is nothing. If so, it sets the Success flag to False, creates an error message, and immediately returns.

As for the use of wildcards, that's standard Windows functionality, so I don't think we're going to do anything to separate that out as an additional action. We can always update the action description though to point it out.
